#! /bin/sh

(sleep 2 && xinput set-prop "Wings Tech Xtrfy M4" "libinput Accel Profile Enabled" 0, 1 && xinput set-prop "Wings Tech Xtrfy M4" "libinput Accel Speed" -0.5) &

# Key repeat on keyboard
(sleep 1 && xset r rate 200 50) &

(xrandr --output DP-0 --mode 5120x1440 --rate 143.99) &

# Kill any old picom instance before starting a new one
killall -q picom
picom --backend glx --vsync --config ~/.config/picom.conf &

# wallpaper
feh --bg-scale /home/ram/Pictures/aishot-840.jpg &

ghostty &
firefox &
dunst &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         6
bspc config normal_border_color "#2e3440"
bspc config focused_border_color  "#88c0d0"

bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_action1 resize_side

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
